name: Kuba Łojewski
description: A political scientist with a passion for tech stuff most people have no idea about.<br> Fascinated with history, likes to cook and fix stuff, keeps to himself
meta_description: "A political scientist with a passion for tech stuff most people have no idea about. Fascinated with history, likes to cook and fix stuff, keeps to himself"


markdown: kramdown
pygments: true
logo: false
paginate: 10
permalink: /:title


# Details for the RSS feed generator
url:            'kubalojewski.pl'
author:         'Kuba Łojewski'
